"""Generate course notes, lessons, slides and handout from docs/course.json.

Run with Python 3.11+. This step uses only the standard library; rendering the
Marp deck is a separate Node task so normal course setup does not depend on Node.
"""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/course.json"
GENERATED = (
    "<!-- Generated by scripts/build_materials.py from docs/course.json. Edit the source. -->"
)


def bullets(values, prefix="-"):
    return "\n".join(f"{prefix} {value}" for value in values)


def commands(values):
    return "```bash\n" + "\n".join(values) + "\n```"


def sources(lesson):
    return " · ".join(f"[{label}]({url})" for label, url in lesson["sources"])


def clock(minutes):
    return f"{minutes // 60}:{minutes % 60:02d}"


def md_link(path, prefix):
    return f"[{path}]({prefix}{path})"


def lesson_text(lesson, prefix="../"):
    rows = [
        f"## {lesson['id'][:2]} · {lesson['title']} — {lesson['minutes']} min",
        "",
        f"**Outcome:** {lesson['objective']}",
        "",
        f"> {lesson['say']}",
        "",
        "### Teaching beats",
        "",
        bullets(lesson["beats"]),
        "",
        "### Explain and show",
        "",
        bullets(lesson["teach"]),
        "",
    ]
    if lesson.get("prompts"):
        rows += ["### Narrow prompts", ""]
        for prompt in lesson["prompts"]:
            rows += [f"> {prompt}", ""]
    rows += [
        "### Completed demo",
        "",
        "Run from the repository root. Live commands make API requests; choose one prepared runtime rather than running every alternative in class.",
        "",
        commands(lesson["commands"]),
        "",
        "**Open:** " + " · ".join(md_link(p, prefix) for p in lesson["inspect"]),
        "",
        "### Exercise",
        "",
        bullets(lesson["exercise"]),
        "",
        "### Expected solution",
        "",
        bullets(lesson["solution"]),
        "",
        f"**Checkpoint:** {lesson['checkpoint']}",
        "",
        f"**Fallback:** {lesson['fallback']}",
        "",
        "**Official references:** " + sources(lesson),
        "",
    ]
    return "\n".join(rows)


def handout_html(data):
    parts = [
        "<!doctype html><html lang='en'><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        f"<title>{html.escape(data['title'])} — class handout</title>",
        "<style>body{font:16px/1.55 system-ui,sans-serif;color:#24211e;background:#faf7f0;max-width:900px;margin:48px auto;padding:0 28px}h1{font-size:42px;line-height:1.1}h2{border-top:3px solid #8f3028;padding-top:24px;margin-top:42px}h3{color:#8f3028}p,li{max-width:80ch}blockquote{border-left:4px solid #8f3028;margin:24px 0;padding-left:20px;font-size:20px}pre{background:#ebe5d9;padding:18px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}a{color:#8f3028}.meta{color:#665e54}section{break-before:page}@media print{body{font-size:11pt;background:white;margin:0;max-width:none}h1{font-size:28pt}h2{margin-top:0}pre{font-size:9pt}a{color:inherit}section{break-before:page}h2,h3{break-after:avoid}li{break-inside:avoid}}</style>",
        f"<h1>{html.escape(data['title'])}</h1><p>{html.escape(data['outcome'])}</p>",
        "<p class='meta'>180 teaching minutes · breaks extra · generated from docs/course.json · documentation checked "
        + data["checked"]
        + "</p>",
        "<p>Run from the repository root. Offline is a deterministic rehearsal; live verification is recorded separately in <a href='../docs/verification.md'>docs/verification.md</a>. Credentials remain server-side.</p>",
    ]
    start = 0
    for lesson in data["lessons"]:
        parts += [
            f"<section><h2>{lesson['id'][:2]} · {html.escape(lesson['title'])}</h2>",
            f"<p class='meta'>{clock(start)}–{clock(start + lesson['minutes'])} · {lesson['minutes']} minutes</p>",
            f"<p><strong>Outcome:</strong> {html.escape(lesson['objective'])}</p>",
            f"<blockquote>{html.escape(lesson['say'])}</blockquote>",
        ]
        for heading, values in [
            ("Explain and show", lesson["teach"]),
            ("Exercise", lesson["exercise"]),
            ("Expected solution", lesson["solution"]),
        ]:
            parts += [
                f"<h3>{heading}</h3><ul>"
                + "".join(f"<li>{html.escape(v)}</li>" for v in values)
                + "</ul>"
            ]
        if lesson.get("prompts"):
            parts += [
                "<h3>Prompts</h3>"
                + "".join(f"<blockquote>{html.escape(v)}</blockquote>" for v in lesson["prompts"])
            ]
        parts += [
            "<h3>Demo commands</h3><pre>" + html.escape("\n".join(lesson["commands"])) + "</pre>",
            f"<p><strong>Checkpoint:</strong> {html.escape(lesson['checkpoint'])}</p>",
            f"<p><strong>Fallback:</strong> {html.escape(lesson['fallback'])}</p>",
            "<p>"
            + " · ".join(
                f"<a href='{html.escape(url, quote=True)}'>{html.escape(label)}</a>"
                for label, url in lesson["sources"]
            )
            + "</p></section>",
        ]
        start += lesson["minutes"]
    parts += ["</html>"]
    return "\n".join(parts) + "\n"


def slide_deck(data):
    slides = [
        """<!-- _class: lead dark -->
<!-- _paginate: false -->
<div class="kicker">O’Reilly live training · Automata Learning Lab</div>

# Building Agents<br>with OpenAI

One research task. Three runtimes.<br>Evidence you can inspect.

<small>180 minutes · breaks extra · source references are clickable</small>""",
        """## What you will leave with

<div class="flow">
<div class="step"><h3>Build</h3><p>A paper + CSV<br>→ a cited brief</p></div>
<div class="arrow">→</div>
<div class="step"><h3>Inspect</h3><p>Tool calls, evidence,<br>state, and failures</p></div>
<div class="arrow">→</div>
<div class="step"><h3>Serve</h3><p>Evaluation + an<br>authenticated app</p></div>
</div>""",
        """## Three ways to run the same task

| Choice | Loop owner | Course state strategy |
|---|---|---|
| Managed Agents API | OpenAI-managed harness | Managed session |
| Responses | Application code | Explicit local history |
| Agents SDK | SDK inside your app | SDK run history |

Alternatives, not mandatory migration stages.<br>
[Official runtime comparison](https://developers.openai.com/api/docs/guides/agents)""",
    ]
    start = 0
    for lesson in data["lessons"]:
        slides.append(f"""<!-- _class: lead dark -->
<div class="kicker">{lesson["id"][:2]} · {clock(start)}–{clock(start + lesson["minutes"])} · {lesson["minutes"]} minutes</div>

## {lesson["title"]}

{lesson["say"]}

<!-- Outcome: {lesson["objective"]} -->""")
        slides.append(
            f"## {lesson['title']}: the useful distinction\n\n"
            + bullets(lesson["slide_takeaways"], "*")
            + "\n\n<small>"
            + sources(lesson)
            + "</small>"
        )
        demo_commands = lesson["commands"][:3]
        if lesson["id"] == "03-responses":
            demo_commands = [lesson["commands"][0], lesson["commands"][2]]
        if lesson["id"] == "06-evaluate":
            demo_commands = lesson["commands"][:2]
        slides.append(
            "<!-- _class: dark -->\n<div class='kicker'>Completed demo · run from the repository root</div>\n\n## Put the behavior on screen\n\n"
            + commands(demo_commands)
            + f"\n\n<small>{lesson['inspect'][0]}</small>\n\n<!-- {' '.join(lesson['beats'])} -->"
        )
        slides.append(
            "## Your turn\n\n"
            + bullets(lesson["exercise"][:2], "*")
            + "\n\n<small>Full steps and worked solutions: lessons/"
            + lesson["id"]
            + "/</small>"
        )
        slides.append(
            "## Before we move on\n\n"
            + lesson["checkpoint"]
            + "\n\n> "
            + lesson["fallback"]
            + "\n\n<!-- Expected solution: "
            + " ".join(lesson["solution"])
            + " -->"
        )
        start += lesson["minutes"]
    slides += [
        """## Five things to demonstrate

* **Evidence:** a claim and its source quotation
* **Tool use:** a real request, handler, and result
* **Continuity:** a follow-up in the same state strategy
* **Failure:** a handled outage or missing-evidence case
* **Evaluation:** fixed cases, results, and remaining limits""",
        """<!-- _class: lead dark -->
<!-- _paginate: false -->
<div class="kicker">Keep building</div>

# Choose the runtime.<br>Keep the evidence.

Course guide · instructor notes · completed demos · exercises<br>
README.md → docs/course-guide.md

<!-- MCP, skills, subagents, voice, retrieval, and ChatKit remain optional extensions. -->""",
    ]
    return (
        "---\nmarp: true\ntitle: Building Agents with OpenAI\ntheme: automata\npaginate: true\nsize: 16:9\nhtml: true\n---\n\n"
        + GENERATED
        + "\n\n"
        + "\n\n---\n\n".join(slides)
        + "\n"
    )


def outputs(data):
    lessons = data["lessons"]
    expected = [
        "00-setup",
        "01-playground",
        "02-managed",
        "03-responses",
        "04-sdk",
        "05-grounding-actions",
        "06-evaluate",
        "07-ship",
    ]
    if [v["id"] for v in lessons] != expected or sum(v["minutes"] for v in lessons) != 180:
        raise ValueError("The course must have the eight agreed lessons and 180 teaching minutes.")
    schedule = ["| Elapsed | Lesson | Minutes |", "|---|---|---|"]
    instructor = [
        GENERATED,
        "# Instructor guide — Building Agents with OpenAI",
        "",
        "Copy this into your teaching notes. Times are elapsed teaching time; add breaks separately. Detailed explanations, exercises, and solutions live in [course-guide.md](course-guide.md).",
        "",
        "## Before learners arrive",
        "",
        "- Read [verification.md](verification.md) and use only the live paths confirmed for this teaching project.",
        "- Run `make setup`, `make rehearse`, and `make test`. Open the deck, two core notebooks, app, and a fallback recording.",
        "- Check signed-in playground controls and managed/model access. Keep the API key on the backend; never project `.env` or classroom token files.",
        "- If a live path fails, switch to the labeled offline rehearsal or a saved capture. Do not troubleshoot credentials on the projector.",
        "- Review token rates if estimating model cost. Unknown prices stay unknown; managed sandbox/tool charges require separate accounting.",
        "",
        "## Teaching timeline",
        "",
    ]
    start = 0
    for lesson in lessons:
        end = start + lesson["minutes"]
        schedule.append(
            f"| {clock(start)}–{clock(end)} | [{lesson['id'][:2]} · {lesson['title']}](../lessons/{lesson['id']}/README.md) | {lesson['minutes']} |"
        )
        instructor += [
            f"- **{clock(start)}–{clock(end)} · {lesson['title']} ({lesson['minutes']} min)**",
            f"  - Say: “{lesson['say']}”",
            f"  - Show: `{lesson['inspect'][0]}`.",
            "  - Run: " + " → ".join(f"`{c}`" for c in lesson["instructor_commands"]) + ".",
            f"  - Ask learners: {lesson['exercise'][0]}",
            f"  - Check: {lesson['checkpoint']}",
            f"  - Fallback: {lesson['fallback']}",
            "",
        ]
        start = end
    instructor += [
        "## If an API call fails",
        "",
        "- No HTTP response / DNS / timeout: diagnose the network path first. Do not label it a quota or key failure.",
        "- 401 / invalid_api_key: the request is not authenticated; fix the server's key configuration without printing it.",
        "- 429 / insufficient_quota: check [billing](https://platform.openai.com/settings/organization/billing) or [spend limits](https://platform.openai.com/settings/organization/limits). This is different from a transient rate limit.",
        "- 429 / rate_limit_exceeded: pace requests, reduce concurrency, and retry with backoff.",
        "- 403 / model_not_found / project mismatch: inspect model, organization, project, and key scope.",
        "- Keep class moving with `uv run python -m course replay` or the offline runtime. See [error codes](https://developers.openai.com/api/docs/guides/error-codes).",
        "",
        "## Close",
        "",
        "- Collect the five-part exit demonstration and a one-sentence runtime choice.",
        "- Run `uv run python -m course cleanup`; close app sessions and stop the local servers.",
        "- Point learners to `optional/` only after the core path is complete.",
        "",
    ]
    guide = [
        GENERATED,
        f"# {data['title']} — course guide",
        "",
        data["outcome"],
        "",
        "**180 teaching minutes; breaks extra.** This is the teaching source rendered from [course.json](course.json); edit that file and run `python scripts/build_materials.py` to keep the guide, lesson notes, deck, and handout aligned. The original accepted plan remains in [original-plan.md](original-plan.md).",
        "",
        "The core path is playground → managed agent → Responses loop → Agents SDK → grounding/actions → evaluation → application. The three runtimes are alternatives. [Official runtime comparison](https://developers.openai.com/api/docs/guides/agents).",
        "",
        "**Verification:** documentation checked "
        + data["checked"]
        + ". Read [verification.md](verification.md) for actual clean-install, test, API, and fallback status. The signed-in playground is a separate instructor check. Offline results never establish live API access or model quality.",
        "",
        "## Schedule",
        "",
        "\n".join(schedule),
        "",
        "## One task throughout",
        "",
        "- Input: `assets/paper.pdf` and `assets/papers_database.csv`.",
        "- Shared behavior: `course/prompts.py`, `course/tools.py`, `course/schemas.py`, and `course/config.py`.",
        "- Deliverable: a brief with sourced claims, exact quotations, missing evidence, limitations, and an action status.",
        "- Classroom limits: bounded input, turns, tool calls, and time; API-specific bounds are explained where used.",
        "- Model: one `OPENAI_MODEL` configuration; default `gpt-6-luna`. Verify project access before class.",
        "",
    ]
    for lesson in lessons:
        guide += [lesson_text(lesson), ""]
    result = {
        "docs/course-guide.md": "\n".join(guide),
        "docs/instructor-guide.md": "\n".join(instructor),
        "presentation/slides.md": slide_deck(data),
        "presentation/handout.html": handout_html(data),
        "presentation/handout.md": "\n".join(guide)
        .replace("](course.json)", "](../docs/course.json)")
        .replace("](original-plan.md)", "](../docs/original-plan.md)")
        .replace("](verification.md)", "](../docs/verification.md)"),
    }
    for lesson in lessons:
        folder = "lessons/" + lesson["id"] + "/"
        result[folder + "README.md"] = (
            GENERATED
            + "\n# "
            + lesson["title"]
            + "\n\n[Course guide](../../docs/course-guide.md) · [Exercise](exercise.md) · [Worked solution](solution.md)\n\n"
            + lesson_text(lesson, "../../")
        )
        result[folder + "exercise.md"] = (
            GENERATED
            + "\n# Exercise — "
            + lesson["title"]
            + "\n\n"
            + bullets(lesson["exercise"])
            + "\n\n**Deliver:** "
            + lesson["checkpoint"]
            + "\n\n[Reveal the worked solution](solution.md).\n"
        )
        result[folder + "solution.md"] = (
            GENERATED
            + "\n# Worked solution — "
            + lesson["title"]
            + "\n\n"
            + bullets(lesson["solution"])
            + "\n\nThese are assessment criteria; live model wording and tool order can vary. Check actual source evidence.\n"
        )
    return {name: content.rstrip() + "\n" for name, content in result.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail when generated material is stale."
    )
    args = parser.parse_args()
    data = json.loads(SOURCE.read_text())
    stale = []
    for name, content in outputs(data).items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Generated material is stale: " + ", ".join(stale))
    print(
        "Course material is current."
        if args.check
        else "Generated eight lessons, course guide, instructor guide, Marp deck, and handout."
    )


if __name__ == "__main__":
    main()
